[general]
default_monitor = 0
default_gamepad = 0

[keyboard]
change_cast = 263
directions = { up = "w", down = "s", left = "a", right = "d" }
buttons = { LP = "i", MP = "o", HP = "p", LK = "j", MK = "k", HK = "l" }

[joystick]
buttons = { LP = 8, MP = 9, HP = 5, LK = 7, MK = 11, HK = 6 }
