[project]
name = "hud-overlay"
version = "1.2.0"
description = "Visualizador gráfico de entradas tipo arcade para joystick o teclado,"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pynput>=1.8.1",
    "raylib>=5.5.0.4",
]

[dependency-groups]
dev = [
    "nuitka[app]>=4.0.8",
]
